### ISSUE TITLE
Add `nonull` to CLI param

### ISSUE THREAD

**Issue by evilebottnawi** [sindresorhus/cpy-cli#7]

**Comment by schnittstabil** [comment]
For the sake of completeness, the default behavior was introduced by:
* [cpy#20: Use bash-style behavior, if src pattern does not match.](https://github.com/sindresorhus/cpy/pull/20), because of
* [cpy#19: CLI fails silently when source file doesn't exist](https://github.com/sindresorhus/cpy/issues/19)

Therefore, `nonull` is already set to `true` at [cli.js#L33](https://github.com/sindresorhus/cpy-cli/blob/v1.0.1/cli.js#L33).

--

That said, I think the current behavior is reasonable for a CLI application.
@evilebottnawi Can you give us some context, why this feature is useful for you?

**Comment by evilebottnawi** [comment]
@schnittstabil i make standard `npm scripts` for fast build sites and sometimes any directories may empty and i got error, try to use `cash-true` unstable and give error on some `window` :cry:

**Comment by schnittstabil** [comment]
Ah, of course `cpy-cli … || true` doesn't help much, because `cpy` may stop copying on first error.

@sindresorhus IMO a `--null` option would be helpful in some cases, I would like to do implement it, if you agree:

```
--null  If a pattern matches no paths, the pattern is ignored, rather than
        used literally as path. 
```

About the naming: `bash` calls this option `nullglob`, thus `--null-glob` also sounds appropriate.

**Comment by sindresorhus** [comment]
@schnittstabil Is there any way we can solve this without an option? If not, we need a clearer name than `--null`.

**Comment by schnittstabil** [comment]
> Is there any way we can solve this without an option?

I'm afraid not, `nonull: true` is reasonable for almost all interactive CLI sessions.

However, in npm scripts it's sometimes fine, that the patterns doesn't match any paths, but e.g. permission errors should still stop the build, thus `cpy … || true` or similar doesn't help.

Naming alternatives:

* `--null-glob` because `bash` naming is similar
* `--ignore-missing` doesn't work very well, it sound like `ENOENT` errors are ignored to me (e.g. because of race conditions)
* `--ignore-???`, phew, maybe `--ignore-no-match`, `--ignore-empty-match`?

**Comment by sindresorhus** [comment]
@schnittstabil It's just slighty annoying as this sets a precedence that every tool that supports globbing would have to implement such option. You know I don't like options.

`--ignore-no-match` sounds good.

**Comment by schnittstabil** [comment]
> It's just slighty annoying as this sets a precedence that every tool that supports globbing…

We might do it by means of globby and environment variables:
```json
   "copy": "GLOBBY_IGNORE_NO_MATCH=yes cpy …"
```

I don't know, whether that's such a good idea though.

**Comment by evilebottnawi** [comment]
@schnittstabil With https://www.npmjs.com/package/cross-env should work fine on all platforms, later tests this solution

**Comment by schnittstabil** [comment]
@evilebottnawi `globby` doesn't support it (yet) - this was just an idea…

**Comment by evilebottnawi** [comment]
@schnittstabil :disappointed:
